version: "3.7"
services:
    # For if you're doing local dev testing with small amounts of data
    base_flask:
        build: .
        entrypoint: /home/geolambda/work/docker-entrypoint.sh
        command: run_flask
        ports:
            - "80:80"
        env_file:
            - .geolambda.env
            - .flask.env
        environment:
            - FLASK_PORT=80
        volumes:
            - ".:/home/geolambda/work"
            - "./logs:/var/log/uwsgi"

    # For PROD-like behaviour on DEV. Also maybe helps prevent "broken pipe" errors from the flask dev server
    base_flask_uwsgi:
        build: .
        entrypoint: /home/geolambda/work/docker-entrypoint.sh
        command: uwsgi
        ports:
            - "5000:5000"
        env_file:
            - .geolambda.env
            - .flask.env
        environment:
            - FLASK_PORT=5000
        volumes:
            - ".:/home/geolambda/work"
            - "./logs:/var/log/uwsgi"
    base_nginx:
        build: nginx/
        volumes:
            - ./nginx/nginx/docker.http.dev.conf:/etc/nginx/conf.d/nginx.conf
            - ./api/scratch:/usr/share/nginx/html
        depends_on:
            - base_flask_uwsgi
        ports:
            - "80:80"

    test:
        image: "mygeolambda:latest"
        entrypoint: bash -c 'pytest test/'
        env_file: .geolambda.env
        volumes:
            - "./lambda:/home/geolambda/lambda"
            - "./test:/home/geolambda/test"

    package27:
        image: "mygeolambda:latest"
        command: lambda-package.sh
        working_dir: /home/geolambda/work
        volumes:
            - ".:/home/geolambda/work"

    package36:
        image: mygeolambda:latest
        command: bash -c "lambda-package.sh 3.6"
        working_dir: /home/geolambda/work
        volumes:
            - ".:/home/geolambda/work"

    testpackage27:
        image: "developmentseed/geolambda-base:latest"
        command: bash -c "python -m pytest test/";
        working_dir: /home/geolambda
        env_file: .geolambda.env
        environment:
            - LD_LIBRARY_PATH=/home/geolambda/lambda/lib
        volumes:
            - "./test:/home/geolambda/test"
            - "./lambda:/home/geolambda/lambda"

    testpackage36:
        image: "developmentseed/geolambda-base:latest"
        command: bash -c "python3 -m pytest test/";
        working_dir: /home/geolambda
        env_file: .geolambda.env
        environment:
            - LD_LIBRARY_PATH=/home/geolambda/lambda/lib
        volumes:
            - "./test:/home/geolambda/test"
            - "./lambda:/home/geolambda/lambda"
